openapi: 3.0.3
info:
  title: Consultazione ANPR API C001
  description: |-
    Servizio per la notifica di un avviso
    Pattern Model applicati:
    - [AUDIT_REST_02 ] Inoltro dati tracciati nel dominio del Fruitore REST con correlazione
    - [BLOCK_REST] Blocking REST
    - [INTEGRITY_REST_02] Integrità del payload messaggio REST in PDND
  version: '1.0.0'
  contact:
    name: API Support
    email: Assistenza.anpr@pec.sogei.it
  termsOfService: 'http://swagger.io/terms/'
  x-api-id: C001
  x-summary: Servizio di notifica
servers:
  - url: 'https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C001–servizioNotifica/v1'
    description: Url di test per Consultazione Enti C001
  - url: 'https://modipa.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C001–servizioNotifica/v1'
    description: Url di esercizio per Consultazione Enti C001
tags:
- name: E002 service
  description: Manage consultazione enti
security:
  - bearerAuth: []
    Agid-JWT-Signature: []
paths:
  /status:
    get:
      summary: Returns the application status
      description: |
        Returns the application status. For testing purposes, it might randomly reply with an error.
      operationId: get_status
      tags:
        - health
      responses:
        '200':
          description: |
            This is the valid status from the server.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/RispostaKO'
  /anpr-service-e002:
    post:
      tags:
        - E002 service
      summary: Trova caso d'uso
      description: Consultazione di un caso d'uso
      operationId: e002
      security:
        - bearerAuth: []
      requestBody:
        required: true
        description: Richiesta da consultare
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RichiestaE002'
      responses:
        "200":
          description: Caso d'uso trovato
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RispostaE002OK'
        "400":
          description: Caso d'uso invalido
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/RispostaKO'
        "404":
          description: Caso d'uso non trovato
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/RispostaKO'
        "500":
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/RispostaKO'
components:
  schemas:
    RichiestaE002:
      type: object
      required:
        - idOperazioneClient
        - criteriRicerca
        - datiRichiesta
      properties:
        idOperazioneClient:
          type: string
          description: Identificativo univoco attribuito all'operazione dall'ente. Deve essere numerico e crescente. Se esiste in ANPR, l'ente riceve come esito la risposta in precedenza fornita da ANPR con lo stesso ID; se non esiste ed e' inferiore all'ultimo inviato, l'elaborazione termina con errore.
        criteriRicerca:
          $ref: '#/components/schemas/TipoCriteriRicercaE002'
        datiRichiesta:
          $ref: '#/components/schemas/TipoDatiRichiestaE002'
    RispostaE002OK:
      type: object
      properties:
        idOperazioneANPR:
          type: string
        listaSoggetti:
          $ref: '#/components/schemas/TipoListaSoggetti'
        listaAnomalie:
          type: array
          items:
            $ref: '#/components/schemas/TipoErroriAnomalia'
    RispostaKO:
      type: object
      properties:
        idOperazioneANPR:
          type: string
        listaErrori:
          type: array
          items:
            $ref: '#/components/schemas/TipoErroriAnomalia'
    TipoCriteriRicercaE002:
      type: object
      properties:
        codiceFiscale:
          type: string
        idANPR:
          type: string
          description: Identificativo Unico Nazionale
        cognome:
          type: string
        senzaCognome:
          type: string
        nome:
          type: string
        senzaNome:
          type: string
        sesso:
          type: string
        datiNascita:
          $ref: '#/components/schemas/TipoDatiNascitaE000'
    TipoDatiRichiestaE002:
      type: object
      required:
        - dataRiferimentoRichiesta
        - casoUso
        - motivoRichiesta
      properties:
        dataRiferimentoRichiesta:
          type: string
          description: Data cui deve essere riferita la versione della scheda anagrafica
          format: YYYY-MM-DD
          example: '2021-11-15'
        motivoRichiesta:
          type: string
          description: campo per l’indicazione obbligatoria del numero di riferimento della pratica per quale è effettuata l’interrogazione (es. numero di protocollo, fascicolo, verbale, etc.)
        casoUso:
          type: string
          description: caso d'uso (es. C001)
    TipoErroriAnomalia:
      type: object
      properties:
        codiceErroreAnomalia:
          type: string
        tipoErroreAnomalia:
          type: string
        testoErroreAnomalia:
          type: string
        oggettoErroreAnomalia:
          type: string
        campoErroreAnomalia:
          type: string
        valoreErroreAnomalia:
          type: string
    TipoListaSoggetti:
      type: object
      properties:
        datiSoggetto:
          type: array
          items:
            $ref: '#/components/schemas/TipoDatiSoggettiEnte' 
    TipoDatiNascitaE000:
      type: object
      properties:
        dataEvento:
          type: string
          format: YYYY-MM-DD
          example: '2021-11-15'
        senzaGiorno:
          type: string
        senzaGiornoMese:
          type: string
        luogoNascita:
          $ref: '#/components/schemas/TipoLuogoNascita3000'  
    TipoLuogoNascita3000:
      type: object
      properties:
        luogoEccezionale:
          type: string
        comune:
          $ref: '#/components/schemas/TipoComune'
        localita:
          $ref: '#/components/schemas/TipoLocalita'  
    TipoComune:
      type: object
      properties:
        nomeComune:
          type: string
        codiceIstat:
          type: string
        siglaProvinciaIstat:
          type: string
        descrizioneLocalita:
          type: string          
    TipoLocalita:
      type: object
      properties:
        descrizioneLocalita:
          type: string
        descrizioneStato:
          type: string
        codiceStato:
          type: string
        provinciaContea:
          type: string
    TipoDatiSoggettiEnte:
      type: object
      properties:
        generalita:
          $ref: '#/components/schemas/TipoGeneralita'
        residenza:
          type: array
          items:
            $ref: '#/components/schemas/TipoResidenza'
        infoSoggettoEnte:
          type: array
          items:
            $ref: '#/components/schemas/TipoInfoSoggettoEnte'
        identificativi:
          $ref: '#/components/schemas/TipoIdentificativi'
    TipoGeneralita:
      type: object
      properties:
        codiceFiscale:
          $ref: '#/components/schemas/TipoCodiceFiscale'
        cognome:
          type: string
        senzaCognome:
          type: string
        nome:
          type: string
        senzaNome:
          type: string
        sesso:
          type: string
        dataNascita:
          type: string
          format: YYYY-MM-DD
          example: '2021-11-15'
        senzaGiorno:
          type: string
        senzaGiornoMese:
          type: string
        luogoNascita:
          $ref: '#/components/schemas/TipoLuogoEvento'
        soggettoAIRE:
          type: string
        annoEspatrio:
          type: string
        idSchedaSoggettoComune:
          $ref: '#/components/schemas/TipoIdSchedaSoggettoComune'
        idSchedaSoggettoANPR:
          type: string
        note:
          type: string        
    TipoResidenza:
      type: object
      properties:
        tipoIndirizzo:
          type: string
        noteIndirizzo:
          type: string
        indirizzo:
          $ref: '#/components/schemas/TipoIndirizzo'
        localitaEstera:
          $ref: '#/components/schemas/TipoLocalitaEstera1'
        presso:
          type: string
        dataDecorrenzaResidenza:
          type: string
          format: YYYY-MM-DD
          example: '2021-11-15'
    TipoInfoSoggettoEnte:
      type: object
      properties:
        id:
          type: string
        chiave:
          type: string
        valore:
          $ref: '#/components/schemas/TipoInfoValore'
        valoreTesto:
          type: string
        valoreData:
          type: string
          format: YYYY-MM-DD
          example: '2021-11-15'
        dettaglio:
          type: string
    TipoIdentificativi:
      type: object
      properties:
        idANPR:
          type: string
    TipoIndirizzo:
      type: object
      properties:
        cap:
          type: string
        comune:
          $ref: '#/components/schemas/TipoComune'
        frazione:
          type: string
        toponimo:
          $ref: '#/components/schemas/TipoToponimo'
        numeroCivico:
          $ref: '#/components/schemas/TipoNumeroCivico'
    TipoIndirizzoEstero:
      type: object
      properties:
        cap:
          type: string
        localita:
          $ref: '#/components/schemas/TipoDatoLocalitaEstera'
        toponimo:
          $ref: '#/components/schemas/TipoToponimoEstero'
    TipoCodiceFiscale:
      type: object
      properties:
        codFiscale:
          type: string
        validitaCF:
          type: string
        dataAttribuzioneValidita:
          type: string
          format: YYYY-MM-DD
          example: '2021-11-15'
    TipoLuogoEvento:
      type: object
      properties:
        luogoEccezionale:
          type: string
        comune:
          $ref: '#/components/schemas/TipoComune'
        localita:
          $ref: '#/components/schemas/TipoLocalita'
    TipoIdSchedaSoggettoComune:
      type: object
      properties:
        idSchedaSoggettoComuneIstat:
          type: string
        idSchedaSoggetto:
          type: string
    TipoLocalitaEstera1:
      type: object
      properties:
        indirizzoEstero:
          $ref: '#/components/schemas/TipoIndirizzoEstero'
        consolato:
          $ref: '#/components/schemas/TipoConsolato'
    TipoInfoValore:
      enum:
      - A
      - "N"
      - S
      type: string
    TipoToponimo:
      type: object
      properties:
        codSpecie:
          type: string
        specie:
          type: string
        specieFonte:
          type: string
        codToponimo:
          type: string
        denominazioneToponimo:
          type: string
        toponimoFonte:
          type: string
    TipoToponimoEstero:
      type: object
      properties:
        denominazione:
          type: string
        numeroCivico:
          type: string
    TipoNumeroCivico:
      type: object
      properties:
        codiceCivico:
          type: string
        civicoFonte:
          type: string
        numero:
          type: string
        metrico:
          type: string
        progSNC:
          type: string
        lettera:
          type: string
        esponente1:
          type: string
        colore:
          type: string
        civicoInterno:
          $ref: '#/components/schemas/TipoCivicoInterno'
    TipoDatoLocalitaEstera:
      type: object
      properties:
        descrizioneLocalita:
          type: string
        descrizioneStato:
          type: string
        codiceStato:
          type: string
        provinciaContea:
          type: string
    TipoConsolato:
      type: object
      properties:
        codiceConsolato:
          type: string
        descrizioneConsolato:
          type: string
    TipoCivicoInterno:
      type: object
      properties:
        corte:
          type: string
        scala:
          type: string
        interno1:
          type: string
        espInterno1:
          type: string
        interno2:
          type: string
        espInterno2:
          type: string
        scalaEsterna:
          type: string
        secondario:
          type: string
        piano:
          type: string
        nui:
          type: string
        isolato:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      description: 'A bearer token in the format of a JWS and conformed to the specifications included in [RFC8725](https://tools.ietf.org/html/RFC8725).'
      scheme: bearer
      bearerFormat: JWT          
    Agid-JWT-Signature:
      type: apiKey
      in: header
      name: Agid-JWT-Signature
      description: |-
        Header della firma di JWS.
        Il valore di questo header è una firma JWS.
        Vedere Modi  [integrity_rest_02] Integrità del payload del messaggio REST in PDND
    Agid-JWT-TrackingEvidence:
      type: apiKey
      in: header
      name: Agid-JWT-TrackingEvidence
      description: |-
        Header della firma di JWS.
        Il valore di questo header è una firma JWS.
        Vedere Modi  [audit_rest_02] Inoltro dati tracciati nel dominio del Fruitore REST con correlazione
        Claim da includere:
            userID, un identificativo univoco dell'utente interno al dominio del fruitore che ha determinato l'esigenza della request di accesso all'e-service dell'erogatore;
            userLocation, un identificativo univoco della postazione interna al dominio del fruitore da cui è avviata l'esigenza della request di accesso all'e-service dell'erogatore;
            LoA, livello di sicurezza o di garanzia adottato nel processo di autenticazione informatica nel dominio del fruitore.

